# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_calculator.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(352, 473)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("calculate.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.lcd = QtGui.QLCDNumber(self.centralwidget)
        self.lcd.setGeometry(QtCore.QRect(20, 10, 311, 81))
        self.lcd.setNumDigits(8)
        self.lcd.setObjectName(_fromUtf8("lcd"))
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 102, 311, 341))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.b1 = QtGui.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("04b_21"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.b1.setFont(font)
        self.b1.setObjectName(_fromUtf8("b1"))
        self.horizontalLayout.addWidget(self.b1)
        self.b2 = QtGui.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("04b_21"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.b2.setFont(font)
        self.b2.setObjectName(_fromUtf8("b2"))
        self.horizontalLayout.addWidget(self.b2)
        self.b3 = QtGui.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("04b_21"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.b3.setFont(font)
        self.b3.setObjectName(_fromUtf8("b3"))
        self.horizontalLayout.addWidget(self.b3)
        self.b_plus = QtGui.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("04b_21"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.b_plus.setFont(font)
        self.b_plus.setObjectName(_fromUtf8("b_plus"))
        self.horizontalLayout.addWidget(self.b_plus)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.b4 = QtGui.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("04b_21"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.b4.setFont(font)
        self.b4.setObjectName(_fromUtf8("b4"))
        self.horizontalLayout_2.addWidget(self.b4)
        self.b5 = QtGui.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("04b_21"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.b5.setFont(font)
        self.b5.setObjectName(_fromUtf8("b5"))
        self.horizontalLayout_2.addWidget(self.b5)
        self.b6 = QtGui.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("04b_21"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.b6.setFont(font)
        self.b6.setObjectName(_fromUtf8("b6"))
        self.horizontalLayout_2.addWidget(self.b6)
        self.b_sub = QtGui.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("04b_21"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.b_sub.setFont(font)
        self.b_sub.setObjectName(_fromUtf8("b_sub"))
        self.horizontalLayout_2.addWidget(self.b_sub)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.b7 = QtGui.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("04b_21"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.b7.setFont(font)
        self.b7.setObjectName(_fromUtf8("b7"))
        self.horizontalLayout_3.addWidget(self.b7)
        self.b8 = QtGui.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("04b_21"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.b8.setFont(font)
        self.b8.setObjectName(_fromUtf8("b8"))
        self.horizontalLayout_3.addWidget(self.b8)
        self.b9 = QtGui.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("04b_21"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.b9.setFont(font)
        self.b9.setObjectName(_fromUtf8("b9"))
        self.horizontalLayout_3.addWidget(self.b9)
        self.b_mul = QtGui.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("04b_21"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.b_mul.setFont(font)
        self.b_mul.setObjectName(_fromUtf8("b_mul"))
        self.horizontalLayout_3.addWidget(self.b_mul)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.b0 = QtGui.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("04b_21"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.b0.setFont(font)
        self.b0.setObjectName(_fromUtf8("b0"))
        self.horizontalLayout_4.addWidget(self.b0)
        self.b_point = QtGui.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("04b_21"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.b_point.setFont(font)
        self.b_point.setObjectName(_fromUtf8("b_point"))
        self.horizontalLayout_4.addWidget(self.b_point)
        self.b_reset = QtGui.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("楷体"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.b_reset.setFont(font)
        self.b_reset.setObjectName(_fromUtf8("b_reset"))
        self.horizontalLayout_4.addWidget(self.b_reset)
        self.b_div = QtGui.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("04b_21"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.b_div.setFont(font)
        self.b_div.setObjectName(_fromUtf8("b_div"))
        self.horizontalLayout_4.addWidget(self.b_div)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.b_eq = QtGui.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("04b_21"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.b_eq.setFont(font)
        self.b_eq.setObjectName(_fromUtf8("b_eq"))
        self.verticalLayout.addWidget(self.b_eq)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "计算器", None))
        MainWindow.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>计算器（加、减、乘、除）</p></body></html>", None))
        self.b1.setText(_translate("MainWindow", "1", None))
        self.b2.setText(_translate("MainWindow", "2", None))
        self.b3.setText(_translate("MainWindow", "3", None))
        self.b_plus.setText(_translate("MainWindow", "+", None))
        self.b4.setText(_translate("MainWindow", "4", None))
        self.b5.setText(_translate("MainWindow", "5", None))
        self.b6.setText(_translate("MainWindow", "6", None))
        self.b_sub.setText(_translate("MainWindow", "-", None))
        self.b7.setText(_translate("MainWindow", "7", None))
        self.b8.setText(_translate("MainWindow", "8", None))
        self.b9.setText(_translate("MainWindow", "9", None))
        self.b_mul.setText(_translate("MainWindow", "*", None))
        self.b0.setText(_translate("MainWindow", "0", None))
        self.b_point.setText(_translate("MainWindow", ".", None))
        self.b_reset.setText(_translate("MainWindow", "清除", None))
        self.b_div.setText(_translate("MainWindow", "/", None))
        self.b_eq.setText(_translate("MainWindow", "=", None))

